Add Docusaurus site
p2panda/handbook pull request #116
Opened 2021-11-11 23:23 UTC by cafca

Todo:

- [ ] Fix landing page TOC
- [ ] Add outline of the whole thing
- [ ] Remove blog articles
- [ ] The footer

2021-12-08 11:25 UTC, adzialocha commented
I've reverted my change and moved back the Docusaurus into its own `website` folder, realized it looks too cluttered next to the more important CoC and Governance documents etc.

2021-12-11 11:35 UTC, cafca commented on website/docs/02-organising-data/queries.md
> +- _a node MUST NOT log the ip address requests were received from_
What do you all think about this?

2021-12-11 11:36 UTC, cafca commented on website/docs/02-organising-data/queries.md
> +    - _instances can be sorted by self-referential orderings_
Capabilities that we have not implemented yet are in _italics_. Should something be added here?

2022-01-24 08:44 UTC, sandreae commented on website/docs/01-writing-data/schemas.md
> +- encode a _relation_ to another _instance_
Should this be changed to:

> encode a _relation_ to another _document_?

2022-01-24 08:55 UTC, sandreae commented on website/docs/02-organising-data/documents-instances.md
> +- an instance is _deleted_ if its document contains a _delete operation_
I would like to chat about/and or suggest some changes for this section, but I don't want to bulldoze in as I think there are many valid understandings here. I'll just add a comment on my understanding for now :+1:

I quite intuitively understand a `Document` as our main data type now (not surprising as I have spent a lot of time in it....), and when a node is queried for data we are requesting the most recent state of that document. In this mental model, an `Instance` kind of loses it's importance, as we just ask for the document at the current moment. I am starting to think of `Instance` as a special case (it's also very interesting) mutable data reference, rather than a core data type.

2022-01-24 08:56 UTC, sandreae commented on website/docs/02-organising-data/queries.md
> +    - _instances can be sorted by self-referential orderings_
I think it's good just like this for now :+1:

2022-01-24 09:03 UTC, sandreae commented on website/docs/overview.md
> +- implemented in Rust but also available in Javascript and TypeScript through WebAssembly bindings with a comfortable TypeScript interface
I like these statements, they're very powerful and direct. I worry that the first one "build applications without building servers" could be interpreted as, "great, I can freeload of other peoples nodes" :-p  Maybe this could be changed to focus on being part of a peer network with no centralised source of authority, cooperatively managing nodes, or running non-resource heavy embedded nodes (without deploying your own server).

2022-01-24 14:03 UTC, cafca commented on website/docs/02-organising-data/documents-instances.md
> +- an instance is _deleted_ if its document contains a _delete operation_
What do you think of Andreas "document view" naming proposal? That would tie these two concepts together more. Querying a node would return the most up to date view of the document.

2022-01-24 14:07 UTC, cafca commented on website/docs/01-writing-data/operations.md
> +- every _delete_ and _update operation_ MUST have a _previous operation_
@sandreae would you mind updating this to explain how "previous operations" is constructed and why it exists?

2022-01-24 14:23 UTC, cafca commented on website/docs/01-writing-data/schemas.md
> +- a schema MUST have at most 1024 fields
Postgres seems to have an upper limit of [1600 columns](https://nerderati.com/2017/01/03/postgresql-tables-can-have-at-most-1600-columns/) so I thought it would be nice to stay clear of that, maybe we should even make it lower but I didn't want to set arbitrary limits here unless there is a good reason.

2022-01-24 14:25 UTC, cafca commented on website/docs/01-writing-data/schemas.md
> +- encode a _relation_ to another _instance_
yup

2022-01-24 14:44 UTC, sandreae commented on website/docs/overview.md
> +- implemented in Rust but also available in Javascript and TypeScript through WebAssembly bindings with a comfortable TypeScript interface
haha, yeh, I'm not exactly worried about freeloaders right now either :rofl: but I do think we need to distinguish what we're suggesting p2panda is for (with our language) from existing cloud infrastructure which people unfamiliar with p2p might already know. If they read "without managing servers" they might be like, "oh, is it like Firebase then"?

2022-01-24 14:45 UTC, sandreae commented on website/docs/01-writing-data/operations.md
> +- every _delete_ and _update operation_ MUST have a _previous operation_
yes, can do!

2022-01-24 14:46 UTC, sandreae commented on website/docs/02-organising-data/documents-instances.md
> +- an instance is _deleted_ if its document contains a _delete operation_
I do quite like that :-]

2022-01-24 14:48 UTC, sandreae commented on website/docs/02-organising-data/queries.md
> +- _a node MUST NOT log the ip address requests were received from_
I'm _sure_ i already replied to this comment.... anyway, I said something about opiniated statements creeping into this, in general, more objective tech doc. I would actually totally support that, it could be a phase of expanding the handbook into real world use cases as well. Especially when we talk about replication and nodes etc.. things get political quickly.

2022-01-31 09:51 UTC, adzialocha commented on website/docs/01-writing-data/schemas.md
> +- the name of a schema MUST match the regular expression `([A-Za-z0-9][A-Za-z0-9\-\/\.]{0,63})`
While hacking on GraphQL I realized `-` is actually not allowed but only underscores: https://spec.graphql.org/October2021/#sec-Names

2022-02-03 13:20 UTC, sandreae requested changes

2022-02-03 13:20 UTC, sandreae commented on website/docs/02-organising-data/documents-instances.md
> +  - when the data is changed it is still the same document
Suggestion:

> when a documents data is mutated it is still the same document

2022-02-03 13:20 UTC, sandreae commented on website/docs/02-organising-data/documents-instances.md
> +## Instances
I hereby vote to change the naming of this abstract concept to `Document View`.

2022-02-03 15:00 UTC, adzialocha requested changes
Hui! I've went through the whole thingy now, its a good base with all important notes of the core specification.

I've made quite a bunch of comments of different kind throughout which could be summarizes as:

* Typos
* Minor additions and changes here and there
* Requests for moving things into separate PRs for now, simply because they are either a) underspecified b) not "speccy" enough
* Naming consistencies / updates

The structure is really good! Sometimes I wondered about some parts (especially around the core data types like key-pairs, entries, operations etc.) which felt more like an overview but then went already deep into the details, even though a subsection for that topic already existed (sometimes with better and more correct definitions there). I can imagine we could delete some of these sentences in the "overviews".

I'm happy to apply the changes of my comments myself, just let me know how you want to handle it @cafca, if you approve with them I'm happy to do it :+1:

And of course this needs a liiiittle bit more clean up of unused code parts from the default Docusaurus starter project (also happy to do it).

2022-02-04 14:10 UTC, sophiiistika commented on website/docs/overview.md
> +- p2panda is gossip-based: without good connectivity between nodes data may only become available much later or not become available as all
Typo: available "at" all

2022-02-04 14:20 UTC, sophiiistika commented on website/docs/01-writing-data/encoding.md
> +  - every author has many [_logs_][logs], each of which contains many _entries_
something like a typo in line 15: logs in [] should be a link? then the link is missing

2022-02-04 14:25 UTC, sophiiistika commented on website/docs/01-writing-data/encoding.md
> +- have a look at the [section][key_pairs] section of this handbook for more detailled information on this topic
the link should be called "key_pairs" instead of "section"

2022-02-04 14:26 UTC, sophiiistika commented on website/docs/01-writing-data/encoding.md
> +- people who use p2panda can have access to more than one key pair, which is why we don't call key pairs _author_, as bamboo does, we call them _key pair_
maybe add: "people who use p2panda can have access to more than one key pair (due to using more than one device that runs p2panda)"

2022-02-04 15:35 UTC, sophiiistika commented on website/docs/01-writing-data/key-pairs.md
> +  - `p2panda` includes functionality to create key pairs
why "p2panda" gets highlighted here with ``?

2022-02-04 15:51 UTC, sophiiistika commented on website/docs/01-writing-data/schemas.md
> +- todo: rules for describing schemas in metaschemas
You mean the todo-comments? I would also keep them out of the official public handbook 👍  where are they collected then?

2022-02-04 16:34 UTC, sophiiistika commented on website/docs/01-writing-data/clients-nodes.md
> +  - disregard of this rule carries the risk of creating forks within a public key's logs. See [Key Groups][key_groups] for way to publish data from multiple devices without transmitting a private key
for consistent format:
- disregard of this rule carries the risk of creating forks within a public key's logs
- see [Key Groups][key_groups] for a way to publish data from multiple devices without transmitting a private key or changing the node used

2022-02-04 17:34 UTC, sophiiistika commented on website/docs/02-organising-data/documents-instances.md
> +  - every change of a document results in a new instance
suggestion: "every change of data of a document results in a new instance"
change or mutation, if Sam suggestion is followed

2022-02-04 19:29 UTC, sophiiistika commented on website/docs/02-organising-data/queries.md
> +- _a node MUST NOT log the ip address requests were received from_
I tend to agree with Andreas, making it its own section, since it's also a bigger topic and for my understanding somehow not part of Queries (only)

2022-02-04 19:36 UTC, sophiiistika commented on website/docs/04-collaboration/reconciliation.md
> +- p2panda is recording _causal information_ as part of operations in order to make reconciliation effective
May be nice to have an example here for "causal information", but not a must.

2022-02-04 19:44 UTC, sophiiistika reviewed
Some minor comments and typo fixes from me :)  for consistency sake: from section "Networking" onwards the bulletpoints start with a capital letter, before that small. Choose one 😁 
Thank you so much for writing everything down, it's very nice work!

2022-02-14 14:52 UTC, cafca commented on website/docs/02-organising-data/queries.md
> +- _a node MUST NOT log the ip address requests were received from_
Moved to https://github.com/p2panda/handbook/issues/135

2022-02-14 14:54 UTC, cafca commented on .github/workflows/deploy.yml
> +      - docuasaurus2
Yes! It's in the PR description :)

2022-02-15 11:17 UTC, cafca commented on website/docs/01-writing-data/encoding.md
> +- data published using bamboo always belongs to the key pair that signed it, this key pair is called _author_ in bamboo
To be sure I understood what you mean:

> data published using bamboo always belongs to the public key that signed it, this key is called _author_ in bamboo

better?

2022-02-15 11:20 UTC, cafca commented on website/docs/01-writing-data/encoding.md
> +- have a look at the [operations][operations] section of this handbook for more detailled information on this topic
This page explains that p2panda uses bamboo to publish data and how bamboo concepts are used in p2panda, that's why there is a section for every concept from bamboo that we use.

2022-02-15 11:22 UTC, cafca commented on website/docs/01-writing-data/encoding.md
> +- have a look at the [operations][operations] section of this handbook for more detailled information on this topic
I see two very different approaches here, this one is starting at the lowest level (encoding/bamboo) - another approach would be starting at a high level (operations).

2022-02-15 11:24 UTC, cafca commented on website/docs/01-writing-data/encoding.md
> +- 512 bit hashes are considered detrimental to user experience because they take up a lot of space when displayed on screen
I would like to add some explanation for why we are changing the original bamboo hash. Maybe it can just be phrased a bit nicer?

2022-02-15 11:25 UTC, adzialocha commented on website/docs/01-writing-data/encoding.md
> +- data published using bamboo always belongs to the key pair that signed it, this key pair is called _author_ in bamboo
Yes!

2022-02-15 11:29 UTC, adzialocha commented on website/docs/01-writing-data/encoding.md
> +- have a look at the [operations][operations] section of this handbook for more detailled information on this topic
> I see two very different approaches here, this one is starting at the lowest level (encoding/bamboo) - another approach would be starting at a high level (operations).

For me it currently convolutes both concepts at the same time, the sentences talk about Entries, Documents, Operations in one go which is both high and low-level.

How about something like this? (if we still want to talk about entries here)

```
### Entries

- p2panda uses Bamboo entries to record changes of data while giving us cryptographic integrity and authenticity
  - every individual change is recorded as a payload of an entry
  - we call these changes _operations_
- have a look at the [operations][operations] section of this handbook for more detailled information on this topic
```

2022-02-15 11:37 UTC, adzialocha commented on website/docs/01-writing-data/encoding.md
> +- 512 bit hashes are considered detrimental to user experience because they take up a lot of space when displayed on screen
Bamboo v2 wanted to clean up that issue that the crypto primitives are hard-coded, so we could also refer to the new definition, which then would be:

"p2panda uses Bamboo with ed25519 as the authorship scheme and YASMF as the hashing scheme."
https://github.com/AljoschaMeyer/bamboo/blob/master/bamboo2_draft.md

2022-02-15 11:48 UTC, cafca commented on website/docs/01-writing-data/encoding.md
> +- have a look at the [operations][operations] section of this handbook for more detailled information on this topic
Yes! This is making it more clear that we are talking about bamboo here.

2022-02-15 13:37 UTC, cafca commented on website/docs/02-organising-data/persistence.md
> +- instances may be persisted by serialising the instance's fields
I think it should be part of the specification because one of our goals is compatibility with Postgres and SQLite. Having that requires thinking about serialisation.

2022-02-15 14:07 UTC, cafca commented on website/docs/03-networking/discovery.md
> +- Nodes can be configured to broadcast connection parameters via DHT
Maybe we can add an implementation status badge to pages that describe features which have not been implemented yet.

2022-02-15 14:08 UTC, cafca commented on website/docs/03-networking/discovery.md
> +- Nodes can be configured to broadcast connection parameters via DHT
<img width="657" alt="image" src="https://user-images.githubusercontent.com/278463/154078301-73d43a85-04aa-472e-a8d1-5de84811d64b.png">

2022-02-15 14:28 UTC, cafca commented on website/docs/overview.md
> +- implemented in Rust but also available in Javascript and TypeScript through WebAssembly bindings with a comfortable TypeScript interface
Moved here: https://github.com/p2panda/handbook/pull/137

2022-02-15 14:34 UTC, cafca commented on website/docs/01-writing-data/schemas.md
> +- todo: rules for describing schemas in metaschemas
🧠 <- :D

2022-02-17 09:21 UTC, adzialocha commented on website/docs/03-networking/discovery.md
> +- Nodes can be configured to broadcast connection parameters via DHT
Haha. Beautiful!

2022-02-17 09:21 UTC, adzialocha commented on website/docs/01-writing-data/encoding.md
> +# Encoding
Ah, I see! Yes, then "Bamboo" is a good title! :+1:

2022-02-17 09:25 UTC, adzialocha commented on website/docs/02-organising-data/persistence.md
> +- instances may be persisted by serialising the instance's fields
I can still imagine building some p2panda node implementation without a SQL database. For our "aquadoggo" reference implementation that statement holds true but I don't know if its interesting to mention it here as it does not affect the core specification?

2022-02-17 09:27 UTC, adzialocha commented on website/docs/02-organising-data/persistence.md
> +- instances may be persisted by serialising the instance's fields
.. or in other words: Maybe we remove it for now and discuss separately how much we think SQL is part of the specification?

2022-02-17 09:27 UTC, adzialocha commented on website/docs/02-organising-data/persistence.md
> +  - todo: specific versions?
See my point above, I would like to discuss this separately when possible.

2022-02-17 14:56 UTC, cafca commented on website/docs/01-writing-data/schemas.md
> +- the name of a schema MUST match the regular expression `([A-Za-z][A-Za-z0-9_]{0,63})`
`{0,63}` zero length 🤡

2022-02-21 14:04 UTC, cafca commented on website/docs/01-writing-data/key-pairs.md
> +  - `p2panda` includes functionality to create key pairs
It is supposed to differentiate between p2panda, the protocol/network and `p2panda`, the Rust+TypeScript library but actually I think that's just not obvious.

2022-02-21 15:21 UTC, cafca commented on website/docs/02-organising-data/persistence.md
> +- instances may be persisted by serialising the instance's fields
I moved the page here: https://github.com/p2panda/handbook/blob/persistence/website/docs/02-organising-data/persistence.md

2022-02-21 15:21 UTC, cafca commented on website/docs/02-organising-data/persistence.md
> +  - todo: specific versions?
I moved the page here: https://github.com/p2panda/handbook/blob/persistence/website/docs/02-organising-data/persistence.md

2022-02-22 14:13 UTC, cafca commented on website/sidebars.js
> +module.exports = sidebars;
I don't get how this works. I could not find out

- What effect does it have that the `tutorialSidebar` key is named that? When I change it to something else the order of items in the handbook sidebar changes. But why?
- Why is dirname `.` for using the `docs` folder?

2022-02-22 14:20 UTC, cafca commented
I think we should merge this PR but not replace the p2panda.org website yet. The landing page in particular needs some updates but I would not like to do that now. I have updated the Github workflow to trigger on changes to `main` but **not** updated the publish directory in the docusaurus config (it's still at /handbook). 

There's one peculiar thing about configuring the sidebar I made a note about above. If you don't know an immediate solution I'm fine with making that an issue and moving forward (as nothing is broken).

I created new PRs for sections where any of you were hesitant to include them.

2022-02-22 20:39 UTC, adzialocha commented on website/sidebars.js
> +module.exports = sidebars;
It's super strange indeed!

The only thing I could find was in the documentation here: https://docusaurus.io/docs/sidebar/autogenerated

```
type SidebarItemAutogenerated = {
  type: 'autogenerated';
  dirName: string; // Source folder to generate the sidebar slice from (relative to docs)
};
```

.. but also not sure what "relative to docs" really means lol.

Anyhow! I've changed the sidebar to a manual one because its easier to have it all in one place instead of `sidebar_position` markers in each file and `_category_.json` files in each folder. If one wants to move something around, insert a doc, change its position etc. it gets hairy and having it in one place is just adding a line.

2022-02-22 20:43 UTC, adzialocha approved these changes
Woho!!!! :fire: :parasol_on_ground: Thank you for taking care of all the comments and clean-ups!

I've changed the sidebar (see comment above) and some minor things.

2022-02-22 20:46 UTC, sandreae approved these changes
Wooohoo! Thank you for this great work! We have such a good spec foundation to build on now. :fireworks:

2022-02-22 21:06 UTC, merged