Update schema page
p2panda/handbook pull request #148
Opened 2022-02-23 12:01 UTC by cafca

In progress PR to update the schema handbook page while we implement application schemas.

2022-02-24 15:09 UTC, sandreae commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
Ah! This is new to me... could you expand a little, my head hurts....

2022-02-24 15:47 UTC, adzialocha requested changes

2022-02-24 15:47 UTC, adzialocha commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
Yeah, I'm not sure if schema fields are identified like that?
I understood them to be identified as `application_schema_field_v1`.

The operation itself referring to that schema would contain the fields (at least):

```
name: str
type: str
```

2022-02-24 15:48 UTC, adzialocha commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
Also, should we  call it `schema_v1` and `schema_field_v1` since we don't have anything else next to application schemas?

2022-02-24 15:50 UTC, sandreae commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
That's what they're called in the PR 👍

2022-02-25 09:53 UTC, cafca commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
Oh no, no head hurting please. We can have versioning for all the things. I think I misread Andreas' comment on [p2panda#211 ](https://github.com/p2panda/p2panda/issues/211#issuecomment-1048779733) to ask for this, my mistake.

2022-02-25 10:21 UTC, adzialocha commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
Not sure if this is already correct. I think the field schema is called `schema_field_v1`?

2022-02-25 10:21 UTC, adzialocha commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
.. or `application_schema_field_v1`

2022-02-25 10:21 UTC, adzialocha commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
Or maybe you can expand @cafca what you mean with `description`?

2022-02-25 10:30 UTC, cafca commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
`application_schema_v1` is an example for a system schema's id (the "application schema" schema in version 1) and `application_schema_description_v1` would then be a field of that schema (the field `description` on the "application schema" version 1)

2022-02-25 10:32 UTC, adzialocha commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
Ah! I think then we have a different understanding of that schema maybe?

As I understand it it would be the name of it would just be `schema_field_v1` (regardless what the field is called its referring to). In the document following the `schema_field_v1` schema we would have the actual name then. For example I can imagine the (minimum) fields would look like that:

```yaml
name: str
type: str
```

I can make a drawing if this helps as well :-D

2022-02-25 10:33 UTC, adzialocha commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
.. and in your concrete `description` case it could look like this:

```yaml
name: "description"
type: "str"
```

2022-02-25 10:33 UTC, cafca commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
Now I'm also confused haha

2022-02-25 10:34 UTC, adzialocha commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
The `schema_v1` schema I'd imagined like that:

```
name: str
description: str
fields: relation_list
```

2022-02-25 10:35 UTC, adzialocha commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
Here are our notes, maybe this helps: https://laub.liebechaos.org/YpWgU4uWSXq8SI4XdhII1g#2-Separate-schema-and-fields-into-two-logs

2022-02-25 10:36 UTC, sandreae commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
This was my understanding so far too :+1:

2022-02-25 10:37 UTC, adzialocha commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
I'll draw something! Wanted to do that anyhow

2022-02-25 10:39 UTC, sandreae commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
Yay, drawings!!!

2022-02-25 10:48 UTC, adzialocha commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
@cafca @sandreae https://whimsical.com/schemas-3e8BPkS2aAry64NFS2ynp4

2022-02-25 11:29 UTC, cafca commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
Ahh, now I get it. No, we're on the same page, I made a bad example because I'm confused by our wording.

2022-02-25 11:44 UTC, cafca commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
This is what it should be I think:

**Operation schema**: 
- the set of rules that _all_ operations must comply with

**(p2panda) schema**: 
- Any set of rules that can be used to validate an operation for a specific use-case. 
- Valid operations yield documents.

**System schema**: 
- Any schema built into p2panda. 
- Valid operations yield system documents.

**Application schema**: 
- Any schema published by users. 
- **Not** the schema used to publish schemas on p2panda. 
- Valid operations yield application documents.

**Meta schema**: 
- A system schema that can be used to publish application schemas. 
- **Not** the set of rules that all operations must comply with.
- Valid operations yield application schemas

**Meta schema field schema (???):** 
- A system schema that can be used to publish field definitions
- Valid operations yield application schema fields, which can be embedded in application schemas.

2022-02-25 11:51 UTC, cafca commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
I think if we are calling it _schema schema_ or just _schema_ instead of _meta schema_ it will be harder to understand what is being referred to because we are also using the word _schema_ to refer to the general concept of schemas.

2022-02-25 12:37 UTC, adzialocha commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
Ah, thats a good list to go through! I have a slighly different understanding.

Can imagine that the underlying  here is that CDDL are "schemas" AND p2panda has "schemas" and they are not (strictly) related.

> **Operation schema**: 
> - the set of rules that _all_ operations must comply with

This is what I understood as the "Meta Schema" so far, but I like "Operation Schema" better. Or how about not even calling it a schema at all? Its a schema in the sense that it is a CDDL schema but maybe we can call it "Operation format" or "Operation data definition" instead?

> **Schema**: 
> - Any set of rules that can be used to validate an operation for a specific use-case. 
> - Valid operations yield documents.
> - **Not** the schema used to publish application schemas

> **System schema**: 
> - Any schema built into p2panda. 
> - Valid operations yield system documents.

:+1:

> **Application schema**: 
> - Any schema published by users. 
> - **Not** the schema used to publish schemas on p2panda. 
> - Valid operations yield application documents.

> **Meta schema**: 
> - A system schema that can be used to publish application schemas. 
> - **Not** the set of rules that all operations must comply with.
> - Valid operations yield application schemas

These two sound very similar, are they the same just in different state? One is the operation, the other the document? I would write instead (and skip "meta schema"):

**Application schema**: 
- Used to publish schemas on p2panda by users
- Refers to application schema fields
- Valid operations yield application schema documents.

> **Meta schema field schema (???):** 
> - A system schema that can be used to publish field definitions
> - Valid operations yield application schema fields, which can be embedded in application schemas.

How about this?

**Application schema field**: 
- A system schema that can be used to publish field definitions
- Valid operations yield application schema fields, which can be referred to in application schemas.

2022-02-25 12:44 UTC, adzialocha commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
Also, the diagram might maybe help to refine our definition? Feel free to add your notes there :+1:

2022-02-25 12:55 UTC, cafca commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
I like "operation format"! It's currently defined [here](https://github.com/p2panda/p2panda/blob/main/p2panda-rs/src/schema/operation.rs#L7) as `OPERATION_SCHEMA`.

2022-02-25 12:59 UTC, cafca commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
> These two sound very similar, are they the same just in different state? One is the operation (following meta schema), the other the document (materialized meta schema operations resulting in application schema documents)? I would write instead (and skip "meta schema"):

They are indeed closely related but I wouldn't go so far as to say they are the same. What I call "application schema" here is a category of things and "meta schema" is a concrete set of rules.

Operations following _the meta schema_ yield _application schemas_.

(I think your last sentence might be missing a word?)

2022-02-25 13:01 UTC, cafca commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
> Application schema:
> - Used to publish schemas on p2panda by users

What do you call the thing that is published then?

2022-02-25 13:04 UTC, cafca commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
> Application schema:
>     Used to publish schemas on p2panda by users
>     Refers to application schema fields
>     Valid operations yield application schema documents.

I think this would be very confusing for developers. They will want to publish data for their application's schema and not for their application's schema document.

2022-02-25 13:06 UTC, adzialocha commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
> Operations following the meta schema yield application schemas.

Yeah, that sounds right as well. The "meta" is somewhat not nice though, because it sounds like its above everything ..

2022-02-25 13:10 UTC, cafca commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
What I prefer in your diagram is reading `schema: schema_v1` instead of `schema: metaschema_v1`  as I had proposed here.

2022-02-25 13:26 UTC, sandreae commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
Hmmm, I need to digest all of this ;-p 

My instinct says we are maybe talking about two layers at the same time which makes it hard to reason about/find a unified naming system. One layer is at the _schema_ level, the definition of operations which arrive to a node (operations of any kind). The other is the materialised documents/views resulting from operations of different types. The two layers are very overlapping/cyclical....

2022-02-25 13:31 UTC, adzialocha commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
This sentence might help to wrap our heads around it:

"I publish operations using the venues schema to get venue documents".

How would you apply this logic pn application schemas?

2022-02-25 13:33 UTC, adzialocha commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
On another note: maybe we don't need a new word for everything in every context, but express the context through how we use the word in a sentence? 🤔😄

2022-02-25 13:35 UTC, adzialocha commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
"I create schemas writing operations following the `schema_v1` system schema." 😵

2022-02-25 13:54 UTC, sandreae commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
I like both those sentences 👍

2022-02-25 13:58 UTC, sandreae commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
I _think_ I don't make much distinction between system or application schemas anymore. Once we have figured out how they are defined, stored and referenced (which is a bit special) then from the onwards (publishing operations, materialising, relations, dependencies) it all becomes the same.

2022-02-25 14:18 UTC, adzialocha commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
> I _think_ I don't make much distinction between system or application schemas anymore. Once we have figured out how they are defined, stored and referenced (which is a bit special) then from the onwards (publishing operations, materialising, relations, dependencies) it all becomes the same.

I agree, especially the tooling around it will abstract this away. Developers might just refer to schemas identified by their id.

2022-02-28 14:51 UTC, adzialocha commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
I thought about this over the weekend. I see now that we're lacking a word for one particular concept (it helped to see it in the diagram!) as @cafca pointed out. I think for the specification it makes sense to give it a name, for the later use of p2panda it will probably not important anymore, but its good to be precise for the specification :+1:

I'd be up for calling the system schema "schema_v1" the "meta schema" or "meta application schema" and what I previously understood as the "meta schema" we call "operation format"?

2022-03-01 16:11 UTC, adzialocha commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
More thinking, related to my comment before: How about calling "meta schema" just "schema format" (similar to "operation format"? It is not really a schema anyhow, at least when we now understand "schema" as the p2panda-thingy and not CDDL.

2022-03-10 11:06 UTC, sandreae commented on website/docs/01-writing-data/schemas.md
> +  - application schemas are uniquely identified by the _document view id_ of their _metaschema_ instance
Not sure if it's right, but for the sake of sharing my understanding of things, this is how I would currently phrase this section:

- _application schema_ are published by developers
  - they are published as reusable data schemas and can be used in many applications
  - they are used to transport application specific data
  - application schemas are uniquely identified by their _document view id_

2022-03-10 11:12 UTC, adzialocha commented on website/docs/01-writing-data/schemas.md
> +  - application schemas are uniquely identified by the _document view id_ of their _metaschema_ instance
> they are used to transport application specific data

Operations are used to transport application specific data. Maybe its better "they are used to validate the format of application specific data"?

2022-03-10 11:59 UTC, sandreae commented on website/docs/01-writing-data/schemas.md
> +  - application schemas are uniquely identified by the _document view id_ of their _metaschema_ instance
:+1: changed that

2022-03-10 22:22 UTC, adzialocha commented on website/docs/01-writing-data/schemas.md
> +    - example `application_schema_v1_description`
This got sorted here: https://github.com/p2panda/p2panda/issues/261 yay!

2022-03-14 10:48 UTC, cafca commented on website/docs/01-writing-data/schemas.md
> +  - application schemas are uniquely identified by the _document view id_ of their _metaschema_ instance
I added this to the schemas page!

2022-03-14 10:58 UTC, adzialocha commented on website/docs/01-writing-data/schemas.md
> +    - may be one of
may -> must?

2022-03-15 18:54 UTC, adzialocha approved these changes
This has it all! Thank you for writing it all down @cafca!

Ill merge this now as it is complete and correct. Any further todos can be done in separate PRs (we already have an issue for it).

2022-03-15 18:54 UTC, merged