Split relations into pinned and unpinned types
p2panda/handbook pull request #155
Opened 2022-03-01 16:19 UTC by adzialocha

2022-03-01 20:16 UTC, sandreae requested changes
Just the accidentally swapped descriptions, otherwise all good 👍

2022-03-01 20:16 UTC, sandreae commented on website/docs/01-writing-data/schemas.md
> +  - unpinned relations define the exact version of the document as a list of document graph tips
I think the pinned / unpinned description is the wrong way round ☺️

2022-03-02 16:35 UTC, adzialocha commented on website/docs/01-writing-data/schemas.md
> +  - unpinned relations define the exact version of the document as a list of document graph tips
Ha, well spotted! I wished markdown was typed then one doesn't make these mistakes :laughing:

2022-03-02 17:53 UTC, sandreae approved these changes

2022-03-02 21:52 UTC, merged