Update documents-instances.md
p2panda/handbook pull request #170
Opened 2022-05-22 08:48 UTC by sandreae

Include changes from https://github.com/p2panda/p2panda/pull/319

2022-05-25 09:21 UTC, cafca requested changes
I may have been a bit vague when I asked whether that PR should have a handbook update. What I was thinking about is the question of what a document view looks like for deleted documents. Currently we have 

> a document view has a value for all fields that are defined by its document's schema

After https://github.com/p2panda/p2panda/pull/319 deleted documents still have a view id but no field values. As the behavior of deleted documents still feel a bit underspecified in p2panda I would like to be precise in that area if possible.

What do you think about 

> - a document view has a value for all fields that are defined by its document's schema unless the document has been deleted
> - a deleted document's view has no values for its fields

open questions:

- what happens when a deleted document receives `update` operations? as it is deleted its fields have no value by definition but does the view id still change? or is it not possible to apply any operation to a deleted document?
- what if there are multiple `delete` operations? does each one create a new document view id or is the document "frozen" after the first one?

2022-05-25 09:21 UTC, cafca commented on website/docs/02-organising-data/documents-instances.md
> +- a document view has the _operation id_ for the _operation_ which transported each fields value
This feels a bit like an implementation feature, doesn't it? As this section is describing the concept of document views in general I would phrase it a bit differently if we feel it's important to include it here, e.g.

> implementations _should_ ensure that for every field of a document view it is possible to identify the operation in which that field was last modified

Even then I don't think we actually need this requirement for p2panda in general.

2022-05-26 18:20 UTC, adzialocha commented
> What do you think about 
> 
> > - a document view has a value for all fields that are defined by its document's schema unless the document has been deleted
> > - a deleted document's view has no values for its fields

Super, this sounds good to me! 👍

> open questions:
> 
> - what happens when a deleted document receives `update` operations? as it is deleted its fields have no value by definition but does the view id still change? or is it not possible to apply any operation to a deleted document?
> - what if there are multiple `delete` operations? does each one create a new document view id or is the document "frozen" after the first one? 

Good questions!

Maybe the rule should be: Consider a document deleted as soon as _any_ DELETE operation was sighted during materialization.

Another rule: It's not allowed to publish a DELETE or UPDATE operation pointing at a DELETE operation as the previous one.

With these rules there can't be two DELETE operations within one operation graph branch, neither an UPDATE after a DELETE - _but_ in separte, multiple branches it might still happen. In this scenario our winning hash will be sorted last in the topological ordering meaning that if some DELETE or UPDATE branches arrive later, they might change the order and indeed change the document view id.

We can't ignore future operations operations and freeze the id, as that would lead to indeterministic behavior across nodes (nodes might wrongly arrive at different state even though they have the same operations, they just came in in different order).

It's an interesting behavior as "deleted" documents can somehow still be "alive". It doesn't change the document itself, neither it affects relations, so I think that all is good here. Pinned relations might still go on and point at a branch of the operation graph which never seen a DELETE operation even though one exists somewhere else ..

We can and maybe should add a third rule which should reject operations on a document if a node knows it got deleted, but of course if the node didn't know that yet we might still arrive at that above scenario.

2022-05-26 18:34 UTC, adzialocha commented
This is a little bit of a rabbit hole, happy to get cafcas additions in this PR and discuss this in a separate boiling pot issue 😅

2022-05-28 07:38 UTC, sandreae commented
@cafca yeh, sorry, I got the wrong end of the stick on this handbook update. I like all your suggestions for changes above, also about scope of what is in the spec, what is implementation specific/optional. I'll make all these changes first thing next week :clap:

2022-05-28 07:56 UTC, adzialocha commented
> This is a little bit of a rabbit hole, happy to get cafcas additions in this PR and discuss this in a separate boiling pot issue sweat_smile

Okay, I moved this discussion here: https://github.com/p2panda/handbook/issues/172

2022-06-01 09:21 UTC, cafca approved these changes

2022-06-01 09:55 UTC, merged