Key group
p2panda/handbook pull request #228
Opened 2022-08-25 13:03 UTC by sandreae

Brings the KeyGroup spec into the handbook.
- needs checking that all definitions and schema are still correct after we adopted pinned owner relations.

2022-08-25 14:34 UTC, cafca commented on website/docs/specification/core-concepts/permissions.md
> +lish operations for that key group's documents when their key group membership doesn't define the required permissions.
The last sentence seems to have been zombie merged.

2022-08-25 15:56 UTC, cafca requested changes
Looks good overall.

2022-08-25 15:56 UTC, cafca commented on website/docs/specification/core-concepts/permissions.md
> +## Schema Field Definition: Field Type `owner`
This section reads like something is missing. There was no description of what a field type owner is? Because of this change I think we should mark this page of the specification a draft specifically, or we would have to add this field type with the others as well.

2022-08-26 09:15 UTC, sandreae commented on website/docs/specification/core-concepts/permissions.md
> +## Schema Field Definition: Field Type `owner`
There wasn't any more description, there was a cddl definition.

I changed the description a little to match current think/relation terminology.  

But yeh, let's mark the page as draft. that's cool.

2022-08-26 09:17 UTC, merged